spring:
  profiles:
    active: urls
  application:
    name: zoom-out
  datasource:
    url: jdbc:h2:mem:zoom_out
    #    url: jdbc:h2:file:./zoom_out_db
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

  output:
    ansi:
      enabled: always

logging:
  level:
    ROOT: info

server:
  port: 8080

