spring:
  application:
    name: basket
  datasource:
    url: jdbc:h2:mem:basket
#    url: jdbc:h2:file:./basket_db
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  output:
    ansi:
      enabled: always

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9002

logging:
  level:
    ROOT: info

management:
  endpoints:
    web:
      exposure:
        include: '*'